services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CodingFreaks\CfCookiemanager\:
    resource: '../Classes/*'

  # dependency injection (override public setting)
  CodingFreaks\CfCookiemanager\Updates\StaticDataUpdateWizard:
    class: CodingFreaks\CfCookiemanager\Updates\StaticDataUpdateWizard
    autowire: true
    public: true
    tags:
      - name: typo3.install.updatewizard
        title: 'Static Data Update Wizard'
        description: 'Updates the data for the Static Data'

  # dependency injection (override public setting)
  CodingFreaks\CfCookiemanager\Controller\CookieSettingsBackendController:
    public: true
    tags: [ 'backend.controller' ]

  dashboard.widget.consentTracking:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $dataProvider: '@CodingFreaks\CfCookiemanager\Widgets\Provider\ConsentTrackingDataProvider'
      $view: '@dashboard.views.widget'
      #$buttonProvider: '@CCodingFreaks\CfCookiemanager\Widgets\Provider\ConsentTrackingButtonProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'consentTracking'
        groupNames: 'general'
        title: 'Cookie Consent Tracking'
        description: 'Optin/Optout Tracking'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'medium'

  CodingFreaks\CfCookiemanager\Utility\RenderUtility:
    autowire: true
    public: true
    arguments:
      $eventDispatcher: '@Psr\EventDispatcher\EventDispatcherInterface'

  CodingFreaks\CfCookiemanager\EventListener\AddIntroJsModule:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent